# Generated by Django 3.2.16 on 2022-10-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='phonenumber',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='info',
            name='place',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
