# Generated by Django 3.2.16 on 2022-10-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Image',
            field=models.ImageField(default='', upload_to='', verbose_name='/jobs'),
            preserve_default=False,
        ),
    ]
