# Generated by Django 3.2.16 on 2022-10-25 09:25

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Image',
            field=models.ImageField(upload_to=job.models.image_upload),
        ),
    ]
