# Generated by Django 3.2.16 on 2022-10-25 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='job',
        ),
    ]
